services:
  accounts:
    image: accounts
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["sh", "-c", "until /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P j@mshedz0d@ -Q 'SELECT 1' > /dev/null 2>&1; do echo 'Waiting for SQL Server...'; sleep 5; done; echo 'SQL ready! Starting app...'; dotnet Accounts.dll"]
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Accounts;User Id=sa;Password=j@mshedz0d@;TrustServerCertificate=true;MultipleActiveResultSets=true;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD="j@mshedz0d@"
      - MSSQL_PID=Express 
    ports:
      - "1433:1433" 
    volumes: 
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
